### ISSUE TITLE
Settings>SpeakEvents "There was an error loading preference bundle for SpeakEvents"

### ISSUE THREAD

**Issue by TDPFlorida** [k3a/SpeakEvents#3]
On one iPhone5 (iOS8.0) this runs great but on the newer one (iPhone6) running iOS10.3.1 jailbroken when I go into Settings>SpeakEvents...I get "There was an error loading preference bundle for SpeakEvents"

I use WinSCP and copy files (probably not all) I still can't get it to work. I've tried...
https://iosgods.com/topic/1013-tutorial-how-to-fix-failed-to-load-preference-bundle-for-x-error/
but nothing?

This MIGHT have something to do with running it on 32(iPhone5) vs. 64(iPhone6) bits? Any direction would be most appreciated.

**Comment by k3a** [comment]
Yes, this is most probably CPU architecture difference problem.
But there may have been some preference system API changes as well and even if you managed to fix the pref bundle to load, SpeakEvents most probably won't "just work".

I no longer maintained this project unfortunately and Apple have probably made many API changes in system frameworks since this tweak was last supported.

**Comment by TDPFlorida** [comment]
Thanks for the rapid reply. So I guess what you're saying is I am screwed? LOL
